package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class ALUForm {
  private JPanel ALUPanel;
  private ByteViewerForm ALUByteViewer;

  private String _aRegisterValue = "00000000";
  private String _bRegisterValue = "00000000";

  public String getALUValue() {
    return ALUByteViewer.getByte();
  }

  public void setARegisterValue(String value) {
    _aRegisterValue = value;
    this.updateALU();
  }

  public void setBRegisterValue(String value) {
    _bRegisterValue = value;
    this.updateALU();
  }

  private void updateALU() {
    int aValue = Integer.parseInt(_aRegisterValue, 2);
    int bValue = Integer.parseInt(_bRegisterValue, 2);
    int sum = aValue + bValue;
    System.out.println(aValue);
    System.out.println(bValue);
    System.out.println(sum);
    System.out.println(Integer.toBinaryString(sum));
    ALUByteViewer.setByte(Integer.toBinaryString(sum));
  }

  private void createUIComponents() {
    ALUByteViewer = new ByteViewerForm();
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    ALUPanel = new JPanel();
    ALUPanel.setLayout(new GridBagLayout());
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    ALUPanel.add(ALUByteViewer.$$$getRootComponent$$$(), gbc);
    final JLabel label1 = new JLabel();
    label1.setText("Arithmetic Logic Unit");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    ALUPanel.add(label1, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return ALUPanel;
  }
}
