package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class ARegisterForm {
  public ALUForm aluForm;

  private JPanel aRegisterPanel;
  private ByteViewerForm aRegisterByteViewer;

  public String getARegisterValue() {
    return aRegisterByteViewer.getByte();
  }

  public void setARegisterValue(String value) {
    aRegisterByteViewer.setByte(value);
    aluForm.setARegisterValue(aRegisterByteViewer.getByte());
  }

  private void createUIComponents() {
    aRegisterByteViewer = new ByteViewerForm();
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    aRegisterPanel = new JPanel();
    aRegisterPanel.setLayout(new GridBagLayout());
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    aRegisterPanel.add(aRegisterByteViewer.$$$getRootComponent$$$(), gbc);
    final JLabel label1 = new JLabel();
    label1.setText("A Register");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    aRegisterPanel.add(label1, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return aRegisterPanel;
  }
}
