package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class ClockForm {
    public ControlSignalForm controlSignalForm;

    private JPanel clockPanel;
    private JButton nextTickButton;

    private void createUIComponents() {
        nextTickButton = new JButton();
        nextTickButton.addActionListener(actionEvent -> controlSignalForm.nextPulse());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        clockPanel = new JPanel();
        clockPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Reloj");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        clockPanel.add(label1, gbc);
        nextTickButton.setText("Next tick");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        clockPanel.add(nextTickButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return clockPanel;
    }

}
