package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class InstructionRegisterForm {
    private JPanel instructionRegisterPanel;
    private ByteViewerForm instructionRegisterByteViewer;

    public String getInstructionRegisterValue() {
        // Only the last 4 bits
        return "0000" + instructionRegisterByteViewer.getByte().substring(4);
    }

    public void setInstructionRegisterValue(String value) {
        instructionRegisterByteViewer.setByte(value);
    }

    private void createUIComponents() {
        instructionRegisterByteViewer = new ByteViewerForm();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        instructionRegisterPanel = new JPanel();
        instructionRegisterPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Instruction Register");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        instructionRegisterPanel.add(label1, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        instructionRegisterPanel.add(instructionRegisterByteViewer.$$$getRootComponent$$$(), gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return instructionRegisterPanel;
    }
}
