package com.uptc.simulator.forms;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainForm {
  private JPanel _mainPanel;
  private ControlSignalForm controlSignalForm;
  private RamForm ramForm;
  private InstructionRegisterForm instructionRegisterForm;
  private ProgramCounterForm programCounterForm;
  private BusForm busForm;
  private ClockForm clockForm;
  private MemoryAddressRegisterForm memoryAddressRegister;
  private ARegisterForm ARegisterForm;
  private ALUForm ALUForm;
  private BRegisterForm BRegisterForm;
  private OutputRegisterForm OutputRegisterForm;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    _mainPanel = new JPanel();
    _mainPanel.setLayout(new GridBagLayout());
    _mainPanel.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    _mainPanel.add(controlSignalForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    _mainPanel.add(ramForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    _mainPanel.add(instructionRegisterForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    _mainPanel.add(busForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    _mainPanel.add(clockForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    _mainPanel.add(memoryAddressRegister.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 0;
    _mainPanel.add(programCounterForm.$$$getRootComponent$$$(), gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 30;
    _mainPanel.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.ipadx = 30;
    _mainPanel.add(spacer2, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 1;
    _mainPanel.add(ARegisterForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 2;
    _mainPanel.add(ALUForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 3;
    _mainPanel.add(BRegisterForm.$$$getRootComponent$$$(), gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 4;
    _mainPanel.add(OutputRegisterForm.$$$getRootComponent$$$(), gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return _mainPanel;
  }

  private void createUIComponents() {
    busForm = new BusForm();
    memoryAddressRegister = new MemoryAddressRegisterForm();
    clockForm = new ClockForm();
    instructionRegisterForm = new InstructionRegisterForm();
    programCounterForm = new ProgramCounterForm();
    ramForm = new RamForm();
    controlSignalForm = new ControlSignalForm();
    ARegisterForm = new ARegisterForm();
    BRegisterForm = new BRegisterForm();
    ALUForm = new ALUForm();
    OutputRegisterForm = new OutputRegisterForm();

    memoryAddressRegister.ramForm = ramForm;

    controlSignalForm.busForm = busForm;
    controlSignalForm.programCounterForm = programCounterForm;
    controlSignalForm.memoryAddressRegisterForm = memoryAddressRegister;
    controlSignalForm.instructionRegisterForm = instructionRegisterForm;
    controlSignalForm.ramForm = ramForm;
    controlSignalForm.aRegisterForm = ARegisterForm;
    controlSignalForm.bRegisterForm = BRegisterForm;
    controlSignalForm.ALUForm = ALUForm;
    controlSignalForm.outputRegisterForm = OutputRegisterForm;

    clockForm.controlSignalForm = controlSignalForm;

    ARegisterForm.aluForm = ALUForm;
    BRegisterForm.aluForm = ALUForm;
  }
}
