package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class MainForm {
  private JPanel _mainForm;

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    _mainForm = new JPanel();
    _mainForm.setLayout(new BorderLayout(0, 0));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return _mainForm;
  }

}
