package com.uptc.simulator.forms;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainForm {
    private JPanel _mainPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        _mainPanel = new JPanel();
        _mainPanel.setLayout(new GridBagLayout());
        _mainPanel.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final ControlSignalForm nestedForm1 = new ControlSignalForm();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        _mainPanel.add(nestedForm1.$$$getRootComponent$$$(), gbc);
        final RamForm nestedForm2 = new RamForm();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        _mainPanel.add(nestedForm2.$$$getRootComponent$$$(), gbc);
        final InstructionRegisterForm nestedForm3 = new InstructionRegisterForm();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        _mainPanel.add(nestedForm3.$$$getRootComponent$$$(), gbc);
        final ProgramCounterForm nestedForm4 = new ProgramCounterForm();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        _mainPanel.add(nestedForm4.$$$getRootComponent$$$(), gbc);
        final BusForm nestedForm5 = new BusForm();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        _mainPanel.add(nestedForm5.$$$getRootComponent$$$(), gbc);
        final ClockForm nestedForm6 = new ClockForm();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        _mainPanel.add(nestedForm6.$$$getRootComponent$$$(), gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return _mainPanel;
    }

}
