package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class MemoryAddressRegister {
    private JPanel memoryAddressRegisterPanel;
    private ByteViewerForm memoryAddressRegisterByteViewer;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        memoryAddressRegisterPanel = new JPanel();
        memoryAddressRegisterPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Memory Address Register");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        memoryAddressRegisterPanel.add(label1, gbc);
        final ByteViewerForm nestedForm1 = new ByteViewerForm();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        memoryAddressRegisterPanel.add(nestedForm1.$$$getRootComponent$$$(), gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return memoryAddressRegisterPanel;
    }

    private void createUIComponents() {
        memoryAddressRegisterByteViewer = new ByteViewerForm();
        memoryAddressRegisterByteViewer.setActiveBits(4);
    }
}
