package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class MemoryAddressRegisterForm {
  public RamForm ramForm;

  private JPanel memoryAddressRegisterPanel;
  private ByteViewerForm memoryAddressRegisterByteViewer;

  private void createUIComponents() {
    memoryAddressRegisterByteViewer = new ByteViewerForm();
    memoryAddressRegisterByteViewer.setActiveBits(4);
  }


  public void setMemoryAddressRegisterValue(String value) {
    memoryAddressRegisterByteViewer.setByte(value);
    ramForm.setValueToAddress(value);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    memoryAddressRegisterPanel = new JPanel();
    memoryAddressRegisterPanel.setLayout(new GridBagLayout());
    final JLabel label1 = new JLabel();
    label1.setText("Memory Address Register");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    memoryAddressRegisterPanel.add(label1, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    memoryAddressRegisterPanel.add(memoryAddressRegisterByteViewer.$$$getRootComponent$$$(), gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return memoryAddressRegisterPanel;
  }

}
