package com.uptc.simulator.forms;

import javax.swing.*;
import java.awt.*;

public class OutputRegisterForm {
  private JPanel outputRegisterPanel;
  private JLabel outputLabel;
  private ByteViewerForm outputRegisterByteViewer;

  public void setOutputRegisterValue(String value) {
    outputRegisterByteViewer.setByte(value);
    outputLabel.setText(String.valueOf(Integer.parseInt(value, 2)));
  }

  private void createUIComponents() {
    outputRegisterByteViewer = new ByteViewerForm();
    outputLabel = new JLabel();
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    outputRegisterPanel = new JPanel();
    outputRegisterPanel.setLayout(new GridBagLayout());
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    outputRegisterPanel.add(outputRegisterByteViewer.$$$getRootComponent$$$(), gbc);
    final JLabel label1 = new JLabel();
    label1.setText("Output Register");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    outputRegisterPanel.add(label1, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    gbc.ipady = 10;
    outputRegisterPanel.add(spacer1, gbc);
    final JLabel label2 = new JLabel();
    label2.setText("Output");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    outputRegisterPanel.add(label2, gbc);
    outputLabel.setText("0");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    outputRegisterPanel.add(outputLabel, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return outputRegisterPanel;
  }
}
